config/routes.rb
Rails.application.routes.draw do
  root to: 'tasks#index'
  resources :tasks
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord

  validates :title, presence: true, length: {maximum: 30}
  validates :start_date, presence: true
  validates :end_date, presence: true
  validate  :validate_start_date_not_past_date, :validate_end_date_not_earier_than_start_date

  def date_format(date)
    date.strftime("%Y年%m月%d日")
  end

  private

  def validate_start_date_not_past_date
    unless start_date.blank?
      errors.add(:start_date, "は、今日より前(過去)の日付を入力できません。") if start_date < Date.today
    end
  end

  def validate_end_date_not_earier_than_start_date
    unless end_date.blank?
      errors.add(:end_date, "は、開始日より後の日付を入力してください") if end_date < start_date
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      flash[:success] = "タスク「#{@task.title}」を追加しました。"
      redirect_to tasks_url
    else
      render :new
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      flash[:success] = "タスク「#{@task.title}」を更新しました。"
      redirect_to tasks_url
    else
      render :edit
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    flash[:success] = "タスク「#{@task.title}」を削除しました。"
    redirect_to tasks_url
  end

  private

  def task_params
    params.require(:task).permit(:title, :start_date, :end_date, :all_day, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = yield(:title) 
      | | TaskApp
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    header
      .header_container.bg_tomato
        h1 Ruby on Rails スケジュール管理アプリ
    main
      .main_container
        - flash.each do |message_type,message|
          = content_tag(:div, message, class: "alert alert-#{message_type}")
        = yield
    footer
      .footer_container.bg_tomato
        h1
          = "現在の日時 : #{Date.today} | スケジュール合計 : #{Task.count}"

app/views/tasks/_form.html.slim
- if task.errors.present?
  ul#error_explanation
    - task.errors.full_messages.each do |message|
      li = message


= form_with model: task, local:true do |f|
  table
    tbody.tbody
      tr.title_table
        th
          = f.label :title
        td
          = f.text_field :title, class: 'form-input'
      tr
        th
          = f.label :start_date, id: 'form_start_date'
        td
          = f.date_field :start_date, class: 'form_calendar'
      tr
        th
          = f.label :end_date, id: 'form_end_date'
        td
          = f.date_field :end_date, class: 'form_calendar'
      tr
        th
          = f.label :all_day, id: 'form_all_day'
        td
          = f.check_box :all_day, class: 'form_check_box', id: 'task_check_box'
          | 終日の場合はチェックを入れます
      tr
        th
          = f.label :description, id: 'form_description'
        td
          = f.text_area :description, class: 'form_input', id: 'task_title'
  = f.submit "スケジュールを#{btn}する", class:'btn btn_green'

app/views/tasks/edit.html.slim
= provide(:title, "編集 ")


h1 スケジュール編集

nav.top_nav
  = link_to 'スケジュール一覧', tasks_path,class: 'btn btn_blue'

=render partial: 'form', locals: {btn: '更新', task: @task}

app/views/tasks/index.html.slim
= provide(:title, "一覧 ")

h1 スケジュール一覧

nav.top_nav
  = link_to '新規登録', new_task_path, class: 'btn btn_blue'


table.table
  thead.thead
      th= Task.human_attribute_name(:id)
      th.title_table= Task.human_attribute_name(:title)
      th= Task.human_attribute_name(:start_date)
      th= Task.human_attribute_name(:end_date)
      th= Task.human_attribute_name(:all_day)
      th= Task.human_attribute_name(:updated_at)
      th.btn_table 確認
      th.btn_table 編集
      th.btn_table 削除c
  tbody.tbody
    - @tasks.each do |task|
      tr
        td= task.id
        td= task.title
        td= task.date_format(task.start_date)
        td= task.date_format(task.end_date)
        - if task.all_day?
          td ○
        - else
          td
        td= task.updated_at.to_s(:datetime_jp)
        td= link_to '確認', task_path(task), class: 'btn btn_blue'
        td= link_to '編集', edit_task_path(task), class: 'btn btn_blue'
        td= link_to '削除', task, method: :delete, data: { confirm: "タスク「#{task.title}」を削除します。よろしいですか？"},  class: 'btn btn_red'

app/views/tasks/new.html.slim
= provide(:title, "新規作成 ")

h1 新規作成

nav.top_nav
  = link_to 'スケジュール一覧', tasks_path,class: 'btn btn_blue'

=render partial: 'form', locals: {btn: '登録', task: @task}

app/views/tasks/show.html.slim
= provide(:title, "詳細 ")

h1 スケジュール詳細

nav.top_nav
  = link_to 'スケジュール一覧', tasks_path,class: 'btn btn_blue'

table.table
  tbody
    tr.title_table
      th= Task.human_attribute_name(:title)
      td= @task.title
    tr
      th= Task.human_attribute_name(:start_date)
      td= @task.date_format(@task.start_date)
    tr
      th= Task.human_attribute_name(:end_date)
      td= @task.date_format(@task.end_date)
    tr
      th= Task.human_attribute_name(:all_day)
      - if @task.all_day?
        td ○
      - else
        td
    tr
      th= Task.human_attribute_name(:description)
      td= simple_format(h(@task.description), {}, sanitize: false, wrapper_tag: "div")

nav.end_nav
  ul
    li.nav_list
      =link_to '編集', edit_task_path(@task),class: 'btn btn_blue'
    li.nav_list
      =link_to '削除', @task, method: :delete, data: { confirm: "タスク「#{@task.title}」を削除します。よろしいですか？"},  class: 'btn btn_red'